name: My first CI

on:
  push:
    branches: [main]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v4.1.1


        with:
          fetch-depth: 0

      - name: Set up JDK 19
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: 19

      - name: Step 3 - Build Maven Project
        run: mvn --batch-mode clean package -DskipTests

      - name: Step 4 - Run test cases
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test








